version: 4.0.0
title: Matheus Batista
description: Developer
url: https://matheusb-comp.github.io
repository: https://github.com/matheusb-comp/matheusb-comp.github.io
google_analytics_id: UA-162463806-1
google_site_verification: 16KE4htz_oG4ToKiLhZ1OQUa0LALy58RdDtpn1beNdw
social:
  name: Matheus Batista
  links:
    - https://www.linkedin.com/in/matheus-a31f
    - https://github.com/matheusb-comp
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-avatar
  - jekyll-seo-tag
exclude:
  - ".gitignore"
  - ".jekyll-cache"
  - CNAME
  - README.md
